using System;
using System.IO;
using Feedback_Flow.Models;
using Feedback_Flow.Services.Interfaces;
using iText.Kernel.Pdf;
using iText.Layout;
using iText.Layout.Element;
using iText.Layout.Properties;

namespace Feedback_Flow.Services
{
    public class PdfGenerationService : IPdfService
    {
        public string GenerateStudentPdf(Student student, string content, string outputFolder)
        {
            if (student == null) throw new ArgumentNullException(nameof(student));
            if (string.IsNullOrWhiteSpace(outputFolder)) throw new ArgumentException("Output folder cannot be empty", nameof(outputFolder));

            // Ensure output folder exists
            if (!Directory.Exists(outputFolder))
            {
                Directory.CreateDirectory(outputFolder);
            }

            string cleanName = student.GetFolderName();
            string fileName = $"{cleanName}_Feedback.pdf";
            string outputPath = Path.Combine(outputFolder, fileName);

            try
            {
                using (var writer = new PdfWriter(outputPath))
                using (var pdf = new PdfDocument(writer))
                using (var document = new Document(pdf))
                {
                    document.Add(
                        new Paragraph($"Feedback for: {student.FullName}")
                            .SetTextAlignment(TextAlignment.CENTER)
                            .SetFontSize(18)
                            .SimulateBold());

                    document.Add(new Paragraph("\n")); // Spacer

                    document.Add(new Paragraph(content ?? "No specific notes provided.")
                        .SetFontSize(12));

                    document.Add(
                        new Paragraph("\nGenerated by Feedback Flow")
                            .SetFontSize(8)
                            .SetTextAlignment(TextAlignment.RIGHT)
                            .SimulateItalic());
                }

                return outputPath;
            }
            catch (Exception ex)
            {
                // Log or display the full exception details
                //var fullError =
                //    $"Error: {ex.Message}\nInner: {ex.InnerException?.Message}\nStack: {ex.StackTrace}";
                throw new IOException(
                    $"Error generating PDF for {student.FullName}: {ex.Message}", ex);
            }
        }
    }
}
